/**
 * The live iimjobs taxonomy — the lists the real post-job form completes against.
 *
 * READ OFF THE PRODUCT, NOT INVENTED. Every list here was extracted from
 * `recruit.iimjobs.com/post-job` on 24 Sep 2026: the locations, industries,
 * functional areas and categories are the arrays bundled into that page, and
 * the skills are `GET /recruiter/{id}/jobtags`, which the form loads on open.
 * Our own mock industries were already a word-for-word subset of `INDUSTRIES`,
 * which is what made it worth taking the rest.
 *
 * A SNAPSHOT, WITH A DATE ON IT. Nothing re-fetches this — the endpoint needs a
 * recruiter session, so there is no script to run in CI. Treat it as a fixture
 * that was true on that date rather than as the authority, and re-pull it the
 * same way if the real lists move.
 *
 * SKILLS ARE CURATED, AND THE CUT IS DELIBERATE. The live list is 2,084 tags,
 * of which roughly a thousand are clinical — Neonatologist, Scrub Nursing,
 * Phacoemulsification Surgery — because iimjobs now serves healthcare hiring.
 * None of it is reachable in this prototype: no generated candidate is a
 * doctor, so completing "car" to "Cardiac Anaesthetist" over "Category
 * Management" would make the bar look rich and behave worse. What is kept is
 * the business, management and technology run (1071 of them), plus the
 * handful of business tags that sit after the clinical block. One junk entry
 * ("mohit", somebody's test) is dropped too.
 *
 * These are iimjobs' lists. hirist's equivalent has not been pulled, so its
 * technology skills still come from the generators in `applicants.ts` — see
 * `vocabularyFor` in `lib/smart-hire.ts`.
 *
 * JOB_TITLES COMES FROM A SECOND PRODUCT. Neither iimjobs nor hirist completes
 * the job title at all — both are free-text boxes — but Naukri's posting form
 * does, against `taxonomy-suggest.naukri.com/suggest/dsCommonSuggester`. That
 * is a typeahead rather than a list: ten results per query, no way to ask for
 * all of it. So the titles below were collected by running 105 seed words
 * across both markets (product, sales, finance, engineer, data, devops, ux …)
 * and merging what came back — a sample of the real taxonomy, not the whole
 * of it, and biased towards those seeds by construction.
 */

/** Where a job can be posted. Cities, states and countries in one list,
 *  exactly as the form offers them. */
export const JOB_LOCATIONS = [
  "Delhi NCR",
  "Mumbai",
  "Bangalore",
  "Hyderabad",
  "Kolkata",
  "Chennai",
  "Pune",
  "Gujarat",
  "Maharashtra",
  "MP",
  "Jaipur",
  "Guwahati",
  "Goa",
  "Chandigarh",
  "Punjab",
  "Haryana",
  "Kerala",
  "Orrisa",
  "Bihar",
  "Jharkhand",
  "UP",
  "Karnataka",
  "Tamil Nadu",
  "Rajasthan",
  "Andhra Pradesh",
  "Telangana",
  "Delhi",
  "Gurgaon/Gurugram",
  "Noida",
  "Greater Noida",
  "Faridabad",
  "Ghaziabad",
  "Jammu & Kashmir",
  "Jammu",
  "Srinagar",
  "Amritsar",
  "Jalandhar",
  "Patiala",
  "Ludhiana",
  "Sonipat",
  "Panipat",
  "Udaipur",
  "Jodhpur",
  "Ahmedabad",
  "Surat",
  "Gandhinagar",
  "Vadodara/Baroda",
  "Haridwar",
  "Dehradun",
  "Uttarakhand",
  "Lucknow",
  "Patna",
  "Ranchi",
  "Jamshedpur",
  "Chhattisgarh",
  "Bhubaneshwar",
  "Nagpur",
  "Nasik",
  "Navi Mumbai",
  "Thane",
  "Cochin/Kochi",
  "Hosur",
  "Hubli",
  "Mysore",
  "Raipur",
  "Trivandrum/Thiruvananthapuram",
  "Vijayawada",
  "Guntur",
  "Vishakhapatnam/Vizag",
  "Aurangabad",
  "Rajkot",
  "Varanasi/Banaras",
  "Warangal",
  "Madurai",
  "Coimbatore",
  "Pondicherry",
  "Cuttack",
  "US",
  "UK",
  "Singapore",
  "Middle East",
  "Africa",
  "Malaysia",
  "EU",
  "Hong Kong",
  "Bahrain",
  "Dubai",
  "Kabul",
  "Kuwait",
  "Nigeria",
  "London",
  "Oman",
  "Muscat",
  "Doha",
  "Qatar",
  "Abu Dhabi",
  "Saudi Arabia",
  "Riyadh",
  "Indonesia",
  "Nepal",
  "Bhutan",
  "Dhaka",
  "Bangladesh",
  "China",
  "Afghanistan",
  "Pakistan",
  "Sri Lanka",
  "Ethiopia",
  "Egypt",
  "Kenya",
  "Nairobi",
  "Tanzania",
  "South Africa",
  "Zimbabwe",
  "Zambia",
  "Philippines",
  "West Bengal",
  "Australia",
  "Indore",
  "Agra",
] as const

/** The company industry on a posting. `COMPANY_INDUSTRIES` in
 *  `applicants.ts` deals a subset of these same strings. */
export const INDUSTRIES = [
  "Banking / Financial Services / Broking",
  "Internet / Online / eCommerce",
  "Healthcare / Medical / Hospital",
  "IT-Software / Software Services",
  "Accounting / Finance / Audit",
  "Consulting",
  "FMCG / Foods / Beverage",
  "IT",
  "Strategy / Management Consulting Firms",
  "Retail",
  "Manufacturing",
  "Education / Teaching / Training",
  "Advertising / PR / MR / Events",
  "KPO / Research / Analytics",
  "Consumer Durables",
  "Real Estate / Property",
  "Media / Dotcom / Entertainment",
  "Insurance",
  "BPO / ITES",
  "Biotechnology & Pharmaceuticals",
  "Logistics / SCM / Freight / Shipping",
  "Construction / Engineering / Cement / Metals",
  "Travel / Hospitality",
  "Telecom -5g/4G",
  "Chemicals / Petrochemical / Plastic / Rubber",
  "Auto / Auto Ancillary",
  "Infrastructure / Oil & Gas / Power / Energy",
  "Industrial Products / Heavy Machinery",
  "Recruitment / Staffing",
  "Hotels / Restaurants / Airlines",
  "Food Processing",
  "Agriculture / Dairy",
  "Electricals / Switchgears",
  "Oil and Gas / Power / Infrastructure / Energy",
  "Textile / Garments / Accessories / Fashion",
  "Courier / Transportation / Freight",
  "Wellness / Fitness / Sports",
  "Medical / Healthcare / Hospital",
  "IT-Hardware and Networking",
  "Semiconductors / Electronics",
  "Renewable energy & Sustainability",
  "NGO / Social Service",
  "Architecture / Interior Design",
  "Legal",
  "Mining / Steel / Shipping",
  "Aviation / Aerospace Firm",
  "Export / Import",
  "Facility Management",
  "Ceramics / Sanitary ware",
  "Defence / Government",
  "Steel",
  "Printing / Packaging",
  "Gems and Jewellery",
  "Publishing",
  "Brewery / Distillery",
  "Office Equipment / Automation",
  "Fertilizers / Pesticides",
  "Water Treatment / Waste Management",
  "Heating Ventilation Air Conditioning",
  "Security / Law Enforcement",
  "Animation",
  "Shipping / Marine",
  "Tyres",
  "Paper",
  "Glass",
  "Other",
] as const

/** What the role does. Required on a real posting, and the thing
 *  `suggest-cat-fa` infers from the title. */
export const FUNCTIONAL_AREAS = [
  "Accounting / Taxation / Audit",
  "Administration",
  "Analytics & Business Intelligence",
  "Banking / Financial Services",
  "Content Writer/ Editors",
  "Corporate Planning / Consulting / Strategy",
  "Design",
  "Education / Language Specialist",
  "Entrepreneur / Businessman / Outside Management Consultant",
  "Executive Assistant/Personal Secretary",
  "Export / Import / Merchandising",
  "Hotels / Restaurant Management",
  "HR / IR",
  "Instructional Designer",
  "Insurance",
  "IT",
  "ITeS / BPO / Customer Service",
  "KPO / Research",
  "Legal / Law / Company Secretary",
  "Marketing / Advertising / Public Relations",
  "Media / Entertainment",
  "Pharma / Biotech / Healthcare / Medical / R&D",
  "Production / Maintenance / Quality Assurance",
  "Purchase / Supply Chain / Logistics",
  "Research & Development",
  "Sales / Business Development / Client Servicing",
  "Top Management",
  "Training & Development",
  "Travel / Hospitality",
  "Visual Merchandising",
  "Presales/RFP",
  "Real Estate/Construction",
  "NGO/Social Services/CSR",
  "Miscellaneous",
  "Product Management",
  "Other",
] as const

/** The eight buckets above functional area. */
export const CATEGORIES = [
  "Finance",
  "Sales & Marketing",
  "Consulting",
  "HR",
  "IT & Systems",
  "Operations",
  "Legal",
  "BPO",
] as const

/** The keyword taxonomy a posting is tagged with — what the live form
 *  suggests once you have typed a title. */
export const SKILL_TAGS = [
  "HR Generalist",
  "HR Business Partner",
  "Recruitment",
  "Talent Acquisition",
  "Talent Management",
  "Employee Engagement",
  "Change Management",
  "Employee Relations",
  "Organization Development",
  "Training and Development",
  "Leadership Development",
  "Learning and Development",
  "HR Jobs in Telecom",
  "HR Jobs in FMCG",
  "HR Jobs in IT/ITeS",
  "Talent Development",
  "Supply Chain",
  "HR Operations",
  "IT Services Marketing",
  "B2B Marketing",
  "Marketing Communications",
  "Public Relations",
  "IT Business Analyst",
  "IT Program Management",
  "Business Analysis",
  "Compensation and Benefits",
  "Compensation and Rewards",
  "Benefits and Rewards",
  "HR Consulting",
  "HR Head",
  "Performance Management",
  "HR Jobs in BFSI",
  "IT Sales",
  "Presales",
  "Solutions Sales",
  "HRIS",
  "Industrial Relations",
  "Labour Laws",
  "Labour Relations",
  "Grievance Handling",
  "HR Compliance",
  "HR Jobs in Mfg",
  "PMS",
  "Consumer Internet",
  "Payroll",
  "Risk Management",
  "Audit",
  "Enterprise Risk",
  "CISA",
  "IT Audit",
  "Expat Management",
  "Global Mobility",
  "IT Quality",
  "QMS",
  "Six Sigma",
  "HR Jobs in Pharma",
  "Solution Design",
  "RFP",
  "IT Product Management",
  "ERP",
  "Information Security",
  "IT Risk Management",
  "Operational Risk",
  "Banking Operations",
  "IT Infrastructure Services Sales",
  "IT Project Management",
  "Delivery Management",
  "Business Intelligence",
  "Data Warehousing",
  "BI/DW",
  "Online Product Management",
  "HR Analytics",
  "IT Strategy",
  "IT Consulting",
  "Client Engagement",
  "Corporate Sales",
  "Basel",
  "Credit Risk",
  "Market Risk",
  "Inside Sales",
  "SAP Services",
  "Project Management",
  "Program Management",
  "Sales HR",
  "Solution Architect",
  "BPR",
  "IT Controls",
  "SOX",
  "Peoplesoft",
  "Bid Management",
  "CA",
  "ICWA",
  "Delivery Head",
  "CTO",
  "CSR",
  "NGO",
  "Social Work",
  "Consulting Sales",
  "Banking",
  "Capital Markets",
  "Research",
  "Retail Banking",
  "Investment Banking",
  "Basel II",
  "MIS",
  "Assurance",
  "Trade Marketing",
  "Channel Management",
  "Equity Research",
  "Business Continuity",
  "Financial Reporting",
  "Sales",
  "FMCG Sales",
  "Corporate Finance",
  "Private Equity",
  "M&A",
  "Consumer Marketing",
  "Quant",
  "Statistics",
  "HFT",
  "Trading",
  "Credit Control",
  "Compliance",
  "Credit Research",
  "Brand Management",
  "Product Development",
  "Executive Assistant",
  "Financial Analysis",
  "Practice Head",
  "Product Control",
  "Modern Trade",
  "Process Excellence",
  "Quality",
  "Lean",
  "Hedge Fund",
  "Budgeting",
  "CRM",
  "Analytics",
  "Online Marketing",
  "OSS/BSS",
  "Internal Control",
  "Payments",
  "Cash Management",
  "Corporate Banking",
  "Advertising",
  "Statutory Audit",
  "Accounting",
  "HR Jobs in Healthcare",
  "HR Jobs in Retail",
  "Mfg/Auto Sales",
  "General Trade",
  "Consumer Insights",
  "Market Research",
  "Derivatives",
  "Origination",
  "Distribution",
  "IT Training",
  "Process Design",
  "TQM",
  "Trade Operations",
  "Procurement",
  "IT Procurement",
  "Production",
  "Treasury",
  "Taxation",
  "Direct Tax",
  "Marketing",
  "CAPEX",
  "Sales Training",
  "ITIL",
  "Customer Service",
  "Wealth Management",
  "EHS",
  "Indirect Taxation",
  "Sales Accounting",
  "Chief Financial Officer",
  "Financial Planning",
  "BFSI Sales",
  "CS",
  "PhD",
  "Migration",
  "Utilities",
  "Fund Management",
  "Risk Analytics",
  "Mobile VAS",
  "Marketing Head",
  "Export",
  "Import",
  "Institutional Sales",
  "Sourcing",
  "IT Marketing",
  "IT Infrastructure",
  "IT Services Sales",
  "Proposal",
  "Product Marketing",
  "Functional Consultant",
  "SAP SD",
  "SAP MM",
  "SAP IS Oil",
  "Blackbelt",
  "IT Operations",
  "IT Security",
  "eCommerce",
  "BPM",
  "IT/Telecom Sales",
  "Fixed Income",
  "Pricing Strategy",
  "Change Delivery",
  "IT Infrastructure Services",
  "eLearning",
  "Lead Generation",
  "EPM",
  "Startup",
  "Consulting - Energy Sector",
  "Consulting - Oil and Gas",
  "SAS",
  "Oracle",
  "International Sales",
  "Sales Head",
  "Costing",
  "Forecasting",
  "Finance and Accounts",
  "IFRS",
  "GAAP",
  "Financial Modeling",
  "Valuation",
  "Credit Analysis",
  "Financial Consulting",
  "Strategy Consulting",
  "Consulting - Consumer Goods",
  "Consulting - Supply Chain",
  "Equity Trading",
  "BPO Sales",
  "Product Management",
  "Consulting - Mfg",
  "SAP FICO",
  "Workforce Planning",
  "Sales Support",
  "FMCG Marketing",
  "Mfg/Auto Marketing",
  "Media Planning",
  "COO",
  "Education Sales",
  "CRM Sales",
  "General Management",
  "Practice Management",
  "PMO",
  "Account Management",
  "Key Account Management",
  "Category Management",
  "Investment Banking Operations",
  "Loan Operations",
  "Project Finance",
  "Trade Sales",
  "Trade Finance",
  "IT Product Sales",
  "Corporate Strategy",
  "Consulting - FMCG",
  "Financial Research",
  "BFSI Marketing",
  "Regulatory Reporting",
  "FX",
  "Financial Control",
  "B2B Sales",
  "Reconciliation",
  "Marketing Analytics",
  "Cost Accounting",
  "Private Banking",
  "Econometrics",
  "IT Jobs in BFSI",
  "Middle Office",
  "Trade Support",
  "Consulting - Auto",
  "Futures & Options",
  "Brokerage",
  "Logistics",
  "Legal Jobs in BFSI",
  "Surveillance",
  "Due Diligence",
  "Microfinance",
  "Statistical Modeling",
  "Fund Raising",
  "Asset Liability Management",
  "Commercial Banking",
  "Corporate Communication",
  "Merchandising",
  "IT Compliance",
  "CISM",
  "Investor Relations",
  "Customer Service Head",
  "Accounts Payable",
  "Risk Modeling",
  "International Marketing",
  "Demand Planning",
  "IT Jobs in Mfg",
  "Consulting - BFSI",
  "Transfer Pricing",
  "Consulting - Healthcare",
  "IT Jobs in Healthcare",
  "Rural Sales",
  "Agri",
  "Transition Management",
  "Media Sales",
  "Technical Support",
  "Consulting - Infra",
  "Fraud Analytics",
  "Sales Promotion",
  "Collateral Management",
  "IT Infrastructure Sales",
  "Actuarial",
  "Equity Sales",
  "Hospitality Sales",
  "Equity Analysis",
  "Financial Operations",
  "Legal Entity Control",
  "Management Accounting",
  "Knowledge Management",
  "Fixed Income Research",
  "Accounts Receivable",
  "Wholesale Banking",
  "Hospitality Marketing",
  "SAP CRM",
  "Online Sales",
  "Consulting - Real Estate",
  "MICE",
  "SAP PP",
  "Credit Appraisal",
  "Credit Rating",
  "Media Marketing",
  "Pricing Analysis",
  "Packaging",
  "Data Analytics",
  "Forensic Technology",
  "Underwriting",
  "Rural Marketing",
  "Liquidity Reporting",
  "Resource Management",
  "AML",
  "Debt Restructure",
  "Billing",
  "SAP Utilities",
  "SAP PM",
  "SAP QM",
  "SAP ABAP",
  "Fraud Analysis",
  "Reinsurance",
  "Revenue Planning",
  "IT Jobs in FMCG",
  "Data Management",
  "Media Relations",
  "Capacity Planning",
  "IT Jobs in Hospitality",
  "CRM Marketing",
  "Sales Planning",
  "Venture Capital",
  "SAP Security",
  "SAP IDM",
  "JD Edwards",
  "Credit Policy",
  "Index Research",
  "Hyperion",
  "HR Jobs in Mfg/Auto",
  "Data Center",
  "Internal Communication",
  "Collection",
  "Prime Brokerage",
  "Option Pricing",
  "SAP HCM",
  "Engineering Services",
  "Structured Finance",
  "Content Management",
  "Banking Head",
  "Client Services",
  "PMP",
  "Technical Architect",
  "Instructional Design",
  "Web Analytics",
  "Customer Experience",
  "SAP EAM",
  "IT Vendor Management",
  "Healthcare Sales",
  "Pharma Sales",
  "Pharma Marketing",
  "Consulting - TMT",
  "Leadership Hiring",
  "Telecom Marketing",
  "Telecom Sales",
  "Equity Derivatives",
  "Campus Hiring",
  "Consulting - eGov/PSU",
  "Infrastructure Finance",
  "Cargo",
  "Commodity Sales",
  "Internal Audit",
  "Reference Data",
  "Legal Head",
  "Vendor Management",
  "Purchase",
  "Campaign Management",
  "Debt Syndication",
  "Macroeconomics",
  "Order Management",
  "BPO Head",
  "BPO Operations",
  "Retail Sales",
  "Settlements",
  "IT Sales Head",
  "MBBS",
  "Asset Management",
  "Voice Operations",
  "Non Voice Operations",
  "Planning",
  "Social Media",
  "Trade Promotion",
  "Network Security",
  "Procurement Head",
  "Safety Management",
  "IT Incident Management",
  "SAP BO",
  "SAP Basis",
  "Industrial Safety",
  "Quality Assurance",
  "AMC",
  "Commodity Trading",
  "SAP EHS",
  "Agri Marketing",
  "IT Asset Management",
  "Material Management",
  "SAP APO",
  "SaaS",
  "Plant Operations",
  "Legal Jobs in FMCG",
  "SAP Treasury",
  "Retail Operations",
  "Operations Head",
  "Workforce Management",
  "Facilities Management",
  "Administration",
  "SAP AMS",
  "IT/Telecom",
  "Maintenance Services",
  "Healthcare Operations",
  "FMCG Operations",
  "Operations",
  "Mfg Operations",
  "Healthcare Marketing",
  "Inventory Management",
  "Insurance Operations",
  "Transport Operations",
  "Credit Operations",
  "Real Estate Operations",
  "Client Management",
  "KYC",
  "Corporate Law",
  "Real Estate Sales",
  "Pharma Operations",
  "Opex",
  "Construction Operations",
  "HR Jobs in Infra",
  "BPO Quality",
  "Quality Control",
  "Warehouse Operations",
  "SAP DP",
  "Freight",
  "Infrastructure Operations",
  "Quality Operations",
  "Supply Chain Head",
  "Commodity Research",
  "Regulatory Compliance",
  "Store Operations",
  "Plant Head",
  "Mortgage Operations",
  "BPO Training",
  "Network Operations",
  "SEM / SEO",
  "Mfg Head",
  "CEO",
  "Telesales",
  "HR Jobs in Hospitality",
  "Digital Marketing",
  "SAP BW",
  "Business Objects",
  "Supply Planning",
  "Education Marketing",
  "CRM Consulting",
  "HR Jobs in Real Estate",
  "SAP HR",
  "Consulting - EPC",
  "Proposal Management",
  "Logistics Head",
  "Bancassurance",
  "Legal Jobs in Healthcare",
  "Industrial Sales",
  "Transfer Agency",
  "BPO Presales",
  "Trade Control",
  "SAP IS",
  "SAP ECC",
  "Consulting - Life Sciences",
  "Option Trading",
  "Service Delivery",
  "Real Estate Marketing",
  "Energy Operations",
  "Contracts",
  "IT Product Marketing",
  "SAP WM",
  "EPC Operations",
  "Sourcing Head",
  "Retail Marketing",
  "Corporate Affairs",
  "Equity Syndication",
  "Event Management",
  "Consulting - Telecom",
  "Consulting - Chemical",
  "SAP BI",
  "Mining Operations",
  "Hospitality Operations",
  "Cost Control",
  "CRM Analytics",
  "SAP PI/XI",
  "SAP BPC",
  "Legal Jobs in IT/ITeS",
  "Litigation",
  "Claims",
  "Agri Sales",
  "Telecom Operations",
  "Business Alliances",
  "Fund Accounting",
  "Liaisoning",
  "Engineering Operations",
  "Estimation",
  "SAP MM/WM",
  "Corporate Actions",
  "SAP SCM",
  "Govt Sales",
  "Solutions Marketing",
  "SAP SRM",
  "Auto Operations",
  "Export Documentation",
  "IT Jobs in Pharma",
  "Security Operations",
  "Client Relationships",
  "Assessment",
  "Freight Forwarding",
  "Mobility",
  "Academia",
  "SAP PP/PQ",
  "FMCD Sales",
  "FMCD Marketing",
  "Project Sales",
  "Portfolio Management",
  "Media Buying",
  "IT Jobs in Retail",
  "Benchmarking",
  "Education Operations",
  "Contract Management",
  "Plant HR",
  "Railway Operations",
  "Legal Jobs in Pharma",
  "IPR",
  "Legal Jobs in Real Estate",
  "Legal Jobs in Hospitality",
  "Data Modeling",
  "Transformation",
  "Commercial",
  "Immigration",
  "Dairy Operations",
  "Fund Administration",
  "IT/Telecom Marketing",
  "Shipping Operations",
  "Legal Jobs in Mfg",
  "Legal Jobs in Telecom",
  "BPO Marketing",
  "Engineering Services Sales",
  "Legal Jobs in Retail",
  "IT Infrastructure Services Marketing",
  "SAP AVM",
  "SAP CS",
  "IT Change Management",
  "SAP FS-CM",
  "Fleet Operations",
  "SAP PS",
  "SAP PLM",
  "Freelance",
  "Travel Operations",
  "Algorithmic Trading",
  "SAP GRC",
  "IT Jobs in Telecom",
  "SAP GTS",
  "SAP FI",
  "SAP BPS",
  "SAP SNP",
  "TPM",
  "Creative",
  "Testing",
  "Legal Jobs in Infra",
  "SAP MDG",
  "SAP EWM",
  "SAP CO",
  "Innovation",
  "SAP PI",
  "SAP FSCM",
  "Big Data",
  "SAP SNC",
  "IT Jobs in Auto",
  "SAP DMS",
  "SQL",
  "Broking",
  "New Product Development",
  "ERP Sales",
  "R&D",
  "Consulting - Pharma",
  "SAP MDM",
  "SAP BPM",
  "IT Jobs in Real Estate",
  "Govt Relations",
  "Legal Jobs in Media",
  "Big4",
  "Legal Jobs in Auto",
  "SAP BODS",
  "SAP RE",
  "SAP ISU",
  "Collection Operations",
  "SAP HANA",
  "SAP EP",
  "SAP JVA",
  "SAP ECM",
  "Ad Sales",
  "SAP OTI",
  "SAP TSW",
  "HR Jobs in Media",
  "Retail Analytics",
  "SAP TM",
  "SAP TRM",
  "SAP CLM",
  "SAP LE",
  "SAP WPB",
  "SAP REFX",
  "SAP ETM",
  "SAP PMS",
  "New Product Design",
  "IPO",
  "HORECA",
  "SAP PO",
  "Design",
  "SAP AFS",
  "SAP PTP",
  "SAP MFG",
  "SAP SOTC",
  "Buying",
  "CIO",
  "SAP TAO",
  "Engineering Services Marketing",
  "IT Jobs in Media",
  "SAP BRF",
  "PPC",
  "SAP OTC",
  "SAP ATR",
  "SAP RTP",
  "SAP EPM",
  "SAP COPA",
  "Media Operations",
  "SAP DBM",
  "SAP MAP",
  "Equity Valuation",
  "CFA",
  "Consulting - ICT",
  "Cost Management",
  "Professional Ethics",
  "SAP FICA",
  "IT Jobs in Infra",
  "Rural Banking",
  "Order To Cash",
  "Procure To Pay",
  "Record To Report",
  "LLB",
  "BPO Solutions",
  "Usage & Retention",
  "VaR",
  "SAP BRIM",
  "Content Writing",
  "Pharmacovigilance",
  "Spend Analysis",
  "Python",
  "SAP PPPI",
  "Loss Forecasting",
  "Cofounder",
  "SAP SUS",
  "SAP BSP",
  "SAP SPP",
  "Source To Pay",
  "Faculty",
  "Customer Success",
  "SAP EM",
  "SAP EDI",
  "Murex",
  "SAP FLC",
  "SAP PCM",
  "SAP POC",
  "SAP WMS",
  "SAP P2P",
  "SAP O2C",
  "SAP B1",
  "Physical Security",
  "Record To Pay",
  "Regulatory Affairs",
  "SAP AM",
  "UI/UX",
  "Sales Strategy",
  "Sales Operations",
  "Category Head",
  "SAP SI",
  "Economic Research",
  "F&B Operations",
  "Salesforce",
  "Mobile Marketing",
  "Economics",
  "Predictive Analytics",
  "Entrepreneur In Residence",
  "IT Marketing Head",
  "Recruitment Sales",
  "Tendering",
  "Data Scientist",
  "Vendor Development",
  "IT Transformation",
  "IT Assessment",
  "Editorial",
  "Investment Research",
  "Data Visualization",
  "Data Mining",
  "Data Science",
  "Machine Learning",
  "After Sales",
  "IT Contract Management",
  "IT Product Development",
  "Franchise Development",
  "Consulting - Retail",
  "Visual Merchandising",
  "Governance",
  "Proprietary Trading",
  "Stress Testing",
  "Retail Planning",
  "Catalog Management",
  "Liquidity Risk Management",
  "Techno Commercial",
  "Process Automation",
  "Robotics",
  "Food Safety",
  "Client Onboarding",
  "Patent",
  "IT Hardware Sales",
  "Digital Transformation",
  "Licensing",
  "Supply Chain Analytics",
  "Email Marketing",
  "Chief Product Officer",
  "Asset Services",
  "Data Architect",
  "Product Pricing",
  "Agile",
  "Scrum Master",
  "IT Governance",
  "Quantitative Trading",
  "CPA",
  "CCAR",
  "Building Material Sales",
  "Content Marketing",
  "Tableau",
  "Leasing",
  "Techno Functional",
  "Java Architect",
  ".NET Architect",
  "Campus Placement",
  "Logistics Sales",
  "Fleet Management",
  "Scrum",
  "Solar Product Sales",
  "Automation",
  "LLM",
  "Real Estate Investment",
  "Economist",
  "Operations Research",
  "Consulting - Utilities",
  "Internet of Things",
  "Growth Hacking",
  "Brand Solutions",
  "Variance Analysis",
  "Stressed Assets",
  "IT Production Support",
  "Master Data Management",
  "Revenue Management",
  "Data Quality",
  "Payment Gateway Sales",
  "Analytics Solutions Sales",
  "Coworking Space Sales",
  "Diversity & Inclusion",
  "Sustainability",
  "Digital Banking",
  "Artificial Intelligence",
  "Employer Branding",
  "Ad Operations",
  "Programmatic Marketing",
  "Building Material Marketing",
  "Content Development",
  "Solar Product Marketing",
  "Forensic Investigation",
  "Forensic",
  "NLP",
  "Trade Surveillance",
  "Event Management Sales",
  "Mechanical",
  "Cyber Security",
  "Sales Analytics",
  "Energy Product Sales",
  "Energy Product Marketing",
  "Production Head",
  "Marketing Automation",
  "Interior Design",
  "Payment Gateway Marketing",
  "Waste Water Operations",
  "BPO Solution Design",
  "BPO Solution Architect",
  "Predictive Modeling",
  "Model Validation",
  "Market Intelligence",
  "BlockChain",
  "Data Governance",
  "Independent Price Verification",
  "Affiliate Marketing",
  "Advocacy",
  "Public Policy",
  "Facility Management Sales",
  "Loss Given Default",
  "Probability of Default",
  "Exposure At Default",
  "VAT",
  "Textile Sales",
  "Analytics Solutions Marketing",
  "Coworking Space Marketing",
  "Recruitment Services Marketing",
  "Source To Contract",
  "Textile Marketing",
  "Route To Market",
  "Chemical Product Sales",
  "MEP",
  "Custody & Fund Services",
  "HVAC",
  "Electrical",
  "Biostatistics",
  "Performance Marketing",
  "Go To Market",
  "Revenue Assurance",
  "Logistics Marketing",
  "Product Analyst",
  "HR Transformation",
  "Securities Operations",
  "Mutual Fund Operations",
  "SAP Hybris",
  "Employee Onboarding",
  "Chemical Product Marketing",
  "Securitization",
  "SAP IBP",
  "Vigilance",
  "Political Consulting",
  "Remittance",
  "Industry 4.0",
  "Chief Information Security Officer",
  "Grant Management",
  "SAP BI/BW",
  "Gaming Operations",
  "Catastrophe Modeling",
  "SAP C4C",
  "Goods & Services Tax",
  "Vendor Onboarding",
  "Basel III",
  "Supply Chain Finance",
  "Packaging Product Sales",
  "Curriculum Design",
  "ESG",
  "SAP CTRM",
  "HR Outsourcing",
  "SAP LMS",
  "SAP CMS",
  "Environmental Planning",
  "Security Services Sales",
  "Waste Management Operations",
  "IT Hardware Marketing",
  "HR Jobs in Education",
  "Loyalty Reward Sales",
  "Loyalty Reward Marketing",
  "Packaging Product Marketing",
  "HR Jobs in Online/eComm",
  "Event Management Marketing",
  "Basel IV",
  "Finance Transformation",
  "PaaS",
  "SAP HXM",
  "SAP BTP",
  "Technology Transfer",
  "SAP CPI",
  "Influencer Marketing",
  "Arbitrage",
  "Business Head",
  "Resolution",
  "Quick Commerce",
  "P&L",
  "Finance Head",
  "Taxation Head",
  "Chief of Staff",
  "P&L Head",
  "D2C",
  "Quality Head",
  "Jewellery Manufacturing",
  "Alternative Investment",
  "Design Head",
  "CHRO",
  "Audit Head",
  "M&A Head",
  "Marketing Services Sales",
  "Growth Marketing",
  "Electronic Product Sales",
  "Compliance Head",
  "Electronic Product Marketing",
  "Alternative Investment Fund",
  "US Taxation",
  "Investment Banking Head",
  "Publishing Services Sales",
  "Australian Taxation",
  "Investor Relations Head",
  "Pharma Project Management",
  "Centre Head",
  "Agriculture Project Management",
  "Family Office Operations",
  "Analytics Head",
  "Renewable Energy Project Management",
  "Infra Project Management",
  "Strategy Head",
  "Civil Project Management",
  "Real Estate Project Management",
  "Healthcare Project Management",
  "Research Head",
  "Oil & Gas Project Management",
  "City Head",
  "Chief Marketing Officer",
  "Revenue Cycle Management",
  "Derivatives Trading",
  "Construction Finance",
  "IT Product Operations",
  "HR Project Management",
  "Chief Risk Officer",
  "Inspection Services",
  "Compensation Planning",
  "Compensation Strategy",
  "Chief Revenue Officer",
  "Credit Head",
  "Construction Project Management",
  "Legal Project Management",
  "Marketing Project Management",
  "Electronic Security Project Management",
  "Agile Training",
  "Administration Head",
  "Business Finance",
  "APAC Taxation",
  "Ad Monetization",
  "Engineering Operations Head",
  "Purchase Head",
  "Dairy Project Management",
  "Power BI",
  "Retail Head",
  "Creative Head",
  "International Taxation",
  "Monitoring & Evaluation",
  "Analyst Relations",
  "Revenue Operations",
  "Land Acquisition",
  "Maintenance Head",
  "Interior Design Sales",
  "Sales Excellence",
  "Finance Project Management",
  "Sales Project Management",
  "Generative AI",
  "Trade Compliance",
  "Post-Merger Integration",
  "Mining Project Management",
  "Packaging Head",
  "Product Operations",
  "eCommerce Head",
  "Institutional Equities",
  "Product Head",
  "Demand Generation",
  "Account Based Marketing",
  "Construction Head",
  "Treasury Head",
  "Presales Head",
  "Engineering Project Management",
  "SAP SAC",
  "SAP CAR",
  "SAP ECP",
  "SAP CFIN",
  "FMCG Project Management",
  "Real Estate Head",
  "UK Taxation",
  "Waste Project Management",
  "Manufacturing Project Management",
  "Investment Promotion",
  "Interior Design Marketing",
  "AI Product Management",
  "AI Transformation",
  "Retail Project Management",
  "Business Operations",
  "Talent Acquisition Head",
  "EV Product Sales",
  "Mobile R&D",
  "Mobile Architecture",
  "Android OS",
  "Chief Investment Officer",
  "Customer Analytics",
  "EV Product Marketing",
  "Collection Analytics",
  "Trade Reporting",
  "Transaction Reporting",
  "SAP CX",
  "Recovery",
  "Account Planning",
  "Total Rewards",
  "Structural Design",
  "Structural Engineering",
  "Structural Analysis",
  "UAE Taxation",
  "Media Project Management",
  "Legal Operations",
  "User Research",
  "Behavioral Research",
  "Community Management",
  "Brand Marketing",
  "EPC Project Management",
  "Trade Life Cycle",
  "SAP Finance",
  "SAP Ariba",
  "Content Head",
  "Content Strategy",
  "AI Product Sales",
  "AI Product Marketing",
  "SAP PP/DS",
  "Plant Safety",
  "Last Mile",
  "Waste Management Services Sales",
  "Real Estate Valuation",
  "AI Governance",
  "SAP CPQ",
  "SAP DM",
  "Sales Transformation",
  "Strategic Finance",
  "Options Trading",
  "Consumer Healthcare",
  "System Design",
  "Launch Management",
  "Medical Devices Sales",
  "AI Program Management",
  "Management Fees",
  "Transaction Advisory",
  "SAP S/4HANA",
  "Corporate Communications",
  "Software Testing",
  "Test Automation",
  "QA Leadership",
  "Strategic Sourcing",
  "Process Transformation",
  "Fund Operations",
  "Markets Risk",
  "SAP Delivery",
] as const

/**
 * What a role is called. Naukri's designation suggester, sampled — see the
 * note at the top of this file.
 *
 * Trimmed the way the skills were: no clinical titles (this prototype has no
 * doctors to find), nothing numbered ("Analyst 2") or longer than four words,
 * and none of the bare seniority words the suggester returns as titles in
 * their own right — "Manager", "Head", "Associate" — which would win every
 * short prefix and chip as nothing anybody is hiring for.
 */
export const JOB_TITLES = [
  "Account Assistant",
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Accounts Officer",
  "Accounts Receivable Analyst",
  "Accounts Receivable Associate",
  "Accounts Receivable Caller",
  "Accounts Receivable Executive",
  "Accounts Receivable Specialist",
  "Administrator",
  "Administrator Associate",
  "Administrator Office Manager",
  "Analyst",
  "Analyst Content Engineering",
  "Analyst Data Intelligence Engineer",
  "Analyst Lead",
  "Analyst Officer",
  "Analyst Team Lead",
  "Analyst Underwriter",
  "Analytics Advisory Analyst",
  "Analytics Advisory Specialist",
  "Analytics And Modeling Associate",
  "Analytics Data Scientist",
  "Analytics Delivery Manager",
  "Analytics Head",
  "Analytics Program Manager",
  "Analytics Project Manager",
  "Analytics Solution Architect",
  "Android Application Developer",
  "Android Architect",
  "Android Developer",
  "Android Developer Lead",
  "Android Lead",
  "Android Mobile Application Developer",
  "Android Native Developer",
  "Android Programmer",
  "Android Software Developer",
  "Android Tester",
  "Architect",
  "Architect Engineer",
  "Architectural Assistant",
  "Architectural Consultant",
  "Architectural Designer",
  "Architectural Draughtsman",
  "Architectural Engineer",
  "Architectural Intern",
  "Architectural Visualizer",
  "Architecture Head",
  "Assistant Account Manager",
  "Assistant Branch Manager",
  "Assistant Human Resource Manager",
  "Assistant Manager",
  "Assistant Operations Manager",
  "Assistant Professor",
  "Assistant Quality Manager",
  "Assistant Sales Manager",
  "Assistant Store Manager",
  "Associate Agency Development Manager",
  "Associate Consultant",
  "Associate Director",
  "Associate Java Developer",
  "Associate Manager",
  "Associate Professor",
  "Associate Recruiter",
  "Associate Sales Manager",
  "Associate Sap Abap Consultant",
  "Audit Accountant",
  "Audit Analyst",
  "Audit Assistant",
  "Audit Associate",
  "Audit Consultant",
  "Audit Executive",
  "Audit Manager",
  "Audit Officer",
  "Audit Specialist",
  "Auditor",
  "Backend Architect",
  "Backend Associate",
  "Backend Coordinator",
  "Backend Executive",
  "Backend Java Developer",
  "Backend Lead",
  "Backend Manager",
  "Backend Officer",
  "Backend Python Developer",
  "Backend Web Developer",
  "Banking Advisor",
  "Banking Analyst",
  "Banking Assistant",
  "Banking Associate",
  "Banking Consultant",
  "Banking Executive",
  "Banking Officer",
  "Banking Relationship Manager",
  "Banking Team Lead",
  "Banking Trainer",
  "Brand Ambassador",
  "Brand Associate",
  "Brand Development Executive",
  "Brand Development Manager",
  "Brand Executive",
  "Brand Manager",
  "Brand Marketing Manager",
  "Brand Promoter",
  "Brand Strategist",
  "Branding Head",
  "Business Analyst",
  "Business Development Associate",
  "Business Development Executive",
  "Business Development Manager",
  "Business Development Officer",
  "Business Head",
  "Business Intelligence Developer",
  "Business Manager",
  "Business Partner",
  "Business System Analyst",
  "Category Account Manager",
  "Category Analyst",
  "Category Buyer",
  "Category Executive",
  "Category Head",
  "Category Lead",
  "Category Management Executive",
  "Category Manager",
  "Category Marketing Manager",
  "Category Sales Manager",
  "Chief Engineer",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Information Officer",
  "Chief Manager",
  "Chief Operating Officer",
  "Chief Staff",
  "Chief Technical Officer",
  "Chief Technology Officer",
  "Cloud Administrator",
  "Cloud Architect",
  "Cloud Consultant",
  "Cloud Data Engineer",
  "Cloud Developer",
  "Cloud Devops Engineer",
  "Cloud Engineer",
  "Cloud Security Architect",
  "Cloud Solutions Architect",
  "Cloud Support Engineer",
  "Communications Account Manager",
  "Communications Administrator",
  "Communications And Outreach Manager",
  "Communications Engineer",
  "Communications Lead",
  "Communications Manager",
  "Communications Professional",
  "Communications Strategist",
  "Communications Supervisor",
  "Communications Trainer",
  "Compliance Analyst",
  "Compliance Associate",
  "Compliance Auditor",
  "Compliance Coordinator",
  "Compliance Engineer",
  "Compliance Executive",
  "Compliance Head",
  "Compliance Manager",
  "Compliance Officer",
  "Compliance Specialist",
  "Consultant",
  "Consultant Architect",
  "Content Analyst",
  "Content Designer",
  "Content Developer",
  "Content Editor",
  "Content Manager",
  "Content Moderator",
  "Content Reviewer",
  "Content Specialist",
  "Content Strategist",
  "Content Writer",
  "Coordinator Intern",
  "Coordinator Trainee",
  "Creative Content Writer",
  "Creative Designer",
  "Creative Director",
  "Creative Graphic Designer",
  "Creative Lead",
  "Creative Manager",
  "Creative Producer",
  "Creative Strategist",
  "Creative Visualizer",
  "Creative Writer",
  "Credit Analyst",
  "Credit and Risk Analyst",
  "Credit Control Executive",
  "Credit Controller",
  "Credit Executive",
  "Credit Manager",
  "Credit Officer",
  "Credit Rating Analyst",
  "Credit Relationship Manager",
  "Credit Risk Manager",
  "Customer Care Executive",
  "Customer Care Representative",
  "Customer Relationship Executive",
  "Customer Relationship Manager",
  "Customer Service Executive",
  "Customer Service Representative",
  "Customer Success Manager",
  "Customer Support Engineer",
  "Customer Support Executive",
  "Customer Support Representative",
  "Data Analyst",
  "Data Architect",
  "Data Engineer",
  "Data Entry Operator",
  "Data Modeller",
  "Data Scientist",
  "Data Stage Developer",
  "Database Administrator",
  "Database Administrator Consultant",
  "Database Analyst",
  "Database Architect",
  "Database Designer",
  "Database Developer",
  "Database Engineer",
  "Database Programmer",
  "Database Support Engineer",
  "Database Tester",
  "Design and Process Engineer",
  "Design and Verification Engineer",
  "Design Architect",
  "Design Draughtsman",
  "Design Engineer",
  "Design Lead",
  "Design Manager",
  "Design Testability Engineer",
  "Designer",
  "Developer",
  "Developer Advocate",
  "Developer Architect",
  "Developer Evangelist",
  "Developer Executive",
  "Developer Intern",
  "Developer Staff",
  "Developer Trainee",
  "Devops Administrator",
  "Devops Analyst",
  "Devops Architect",
  "Devops Consultant",
  "Devops Developer",
  "Devops Engineer",
  "Devops Lead",
  "Devops Manager",
  "Devops Specialist",
  "Devops Support Engineer",
  "Digital Account Manager",
  "Digital Analyst",
  "Digital Artist",
  "Digital Marketer",
  "Digital Marketing Analyst",
  "Digital Marketing Consultant",
  "Digital Marketing Executive",
  "Digital Marketing Manager",
  "Digital Marketing Specialist",
  "Digital Marketing Strategist",
  "Director Engineering",
  "Director Human Resources",
  "Director Information Director",
  "Director Marketing",
  "Director Marketing and Sales",
  "Director Operation",
  "Director Products",
  "Director Projects",
  "Director Technology",
  "Engineer",
  "Engineer Trainee",
  "Engineering Head",
  "Engineering Manager",
  "Engineering Program Manager",
  "Engineering Recruiter",
  "Executive Assistant",
  "Executive Assistant To Director",
  "Executive Consultant",
  "Executive Human Resource Generalist",
  "Executive Recruiter",
  "Executive Sales Officer",
  "Executive Sales Trainee",
  "Executive Secretary",
  "Finance Assistant",
  "Finance Business Partner",
  "Finance Director",
  "Finance Executive",
  "Finance Functional Consultant",
  "Finance Head",
  "Finance Lead",
  "Finance Manager",
  "Finance Officer",
  "Finance Specialist",
  "Frontend Architect",
  "Frontend Designer",
  "Frontend Developer Intern",
  "Frontend Development Manager",
  "Frontend Engineer Lead",
  "Frontend Manager",
  "Frontend Software Developer",
  "Frontend Team Lead",
  "Frontend Web Designer",
  "Frontend Web Developer",
  "Full Stack .Net Developer",
  "Fullstack Architect",
  "Fullstack Developer",
  "Fullstack Engineer",
  "Fullstack Javascript Developer",
  "Fullstack Lead",
  "Fullstack Python Developer",
  "Fullstack Software Developer",
  "Fullstack Ui Developer",
  "Fullstack Web Developer",
  "General Administrator",
  "General Manager",
  "General Manager Human Resource",
  "General Manager Operations",
  "General Manager Sales",
  "Growth And Marketing Lead",
  "Growth And Marketing Manager",
  "Growth Development Executive",
  "Growth Development Manager",
  "Growth Executive",
  "Growth Hacker Intern",
  "Growth Manager",
  "Growth Marketing Manager",
  "Growth Officer",
  "Growth Strategy Manager",
  "Head Branch Operations",
  "Head Delivery",
  "Head Digital Marketing",
  "Head Human Resource",
  "Head Operations",
  "Head Recruitment",
  "Head Store",
  "Head Talent Acquisition",
  "Head Technology",
  "Hr Abap Consultant",
  "HR and Accountant",
  "Hr Assistant",
  "Hr Business Analyst",
  "Hr Data Analyst",
  "Hr Fresher",
  "Hr Functional Consultant",
  "Hris Analyst",
  "HRM Consultant",
  "HRM Functional Consultant",
  "Insurance Advisor",
  "Insurance Agent",
  "Insurance and Sales Manager",
  "Insurance Broker",
  "Insurance Executive",
  "Insurance Manager",
  "Insurance Officer",
  "Insurance Relationship Manager",
  "Insurance Sales Officer",
  "Insurance Trainer",
  "Investment Advisor",
  "Investment Analyst",
  "Investment Banker",
  "Investment Banking Analyst",
  "Investment Banking Associate",
  "Investment Consultant",
  "Investment Counselor",
  "Investment Manager",
  "Investment Officer",
  "Investment Specialist",
  "Ios Application Developer",
  "iOS Developer",
  "Ios Engineer",
  "Ios Lead",
  "iOS Mobile Application Developer",
  "iOS Programmer",
  "Ios Software Developer",
  "iOS Team Lead",
  "Ios Tester",
  "iOS Trainee",
  "Java Architect",
  "Java Back End Developer",
  "Java Developer",
  "Java Full Stack Developer",
  "Java Lead",
  "Java Programmer",
  "Java Script Developer",
  "Java Technical Lead",
  "Key Accounts Executive",
  "Key Accounts Manager",
  "Key Accounts Officer",
  "Key Accounts Partner",
  "Key Accounts Specialist",
  "Key Agency Manager",
  "Key Business Manager",
  "Key Client Manager",
  "Key Relationship Manager",
  "Lead Architect",
  "Lead Auditor",
  "Lead Developer",
  "Lead Engineer",
  "Lead Generation Executive",
  "Lead Generation Specialist",
  "Lead Generator",
  "Lead Recruiter",
  "Lead Software Engineer",
  "Legal Advisor",
  "Legal Assistant",
  "Legal Associate",
  "Legal Consultant",
  "Legal Counselor",
  "Legal Entity Controller",
  "Legal Executive",
  "Legal Head",
  "Legal Manager",
  "Legal Officer",
  "Logistics And Warehouse Manager",
  "Logistics Coordinator",
  "Logistics Engineer",
  "Logistics Executive",
  "Logistics Head",
  "Logistics Incharge",
  "Logistics Manager",
  "Logistics Officer",
  "Logistics Specialist",
  "Logistics Supervisor",
  "Machine Designer",
  "Machine Learning Developer",
  "Machine Learning Engineer",
  "Machine Learning Trainer",
  "Machine Maintenance Engineer",
  "Machine Operator",
  "Machine Shop Engineer",
  "Machine Shop Incharge",
  "Machine Shop Manager",
  "Machine Technician",
  "Manager Architect",
  "Manager Buyer",
  "Manager Civil",
  "Manager Controller",
  "Manager Fp&A",
  "Manager Hrbp",
  "Manager Hrd",
  "Manager Materials",
  "Manager Qs",
  "Manufacturing Assistant",
  "Manufacturing Chemist",
  "Manufacturing Consultant",
  "Manufacturing Engineer",
  "Manufacturing Executive",
  "Manufacturing Manager",
  "Manufacturing Officer",
  "Manufacturing Operator",
  "Manufacturing Supervisor",
  "Manufacturing Technician",
  "Marketing Analyst",
  "Marketing Associate",
  "Marketing Coordinator",
  "Marketing Engineer",
  "Marketing Executive",
  "Marketing Head",
  "Marketing Manager",
  "Marketing Officer",
  "Marketing Representative",
  "Marketing Specialist",
  "Media Analyst",
  "Media Buyer",
  "Media Designer",
  "Media Developer",
  "Media Executive",
  "Media Head",
  "Media Manager",
  "Media Sales Executive",
  "Media Specialist",
  "Media Strategist",
  "Merchandiser",
  "Merchandiser Analyst",
  "Merchandiser Associate",
  "Merchandiser Intern",
  "Merchandiser Officer",
  "Merchandiser Promoter",
  "Merchandiser Specialist",
  "Merchandiser Supervisor",
  "Merchandiser Trainee",
  "Mobile Application Designer",
  "Mobile Application Developer",
  "Mobile Application Tester",
  "Mobile Architect",
  "Mobile Automation Tester",
  "Mobile Developer",
  "Mobile Engineer",
  "Mobile Software Engineer",
  "Mobile Test Engineer",
  "Mobile Tester",
  "National Account Manager",
  "National Business Head",
  "National Business Manager",
  "National Credit Manager",
  "National Head",
  "National Key Account Manager",
  "National Manager",
  "National Marketing Manager",
  "National Relationship Manager",
  "National Sales Manager",
  "Network Administrator",
  "Network and Security Specialist",
  "Network Architect",
  "Network Engineer",
  "Network Security Administrator",
  "Network Security Consultant",
  "Network Security Engineer",
  "Network Specialist",
  "Network Support Engineer",
  "Node Engineer",
  "Node Js Backend Developer",
  "Node Js Developer",
  "Node Lead",
  "Officer Incharge",
  "Officer Industrial Engineer",
  "Officer Sales Coordinator",
  "Officer Trainee",
  "Operations Administrator",
  "Operations Analyst",
  "Operations And Maintenance Engineer",
  "Operations and Support Engineer",
  "Operations Coordinator",
  "Operations Executive",
  "Operations Manager",
  "Operations Officer",
  "Operations Team Lead",
  "Operations Team Manager",
  "Partner Account Manager",
  "Partner Development Manager",
  "Partner Management Associate",
  "Partner Operations Specialist",
  "Partner Success Manager",
  "Partner Technical Consultant",
  "Partnership Lead",
  "Partnership Manager",
  "Partnership Officer",
  "Plant Accountant",
  "Plant and Maintenance Engineer",
  "Plant Controller",
  "Plant Engineer",
  "Plant Head",
  "Plant Human Resource Manager",
  "Plant Incharge",
  "Plant Manager",
  "Plant Operator",
  "Plant Supervisor",
  "Platform Administrator",
  "Platform Analyst",
  "Platform Architect",
  "Platform Developer",
  "Platform Engineer",
  "Platform Lead",
  "Platform Manager",
  "Platform Operations Engineer",
  "Platform Specialist",
  "Platform Support Engineer",
  "President",
  "President Commercial",
  "President Finance",
  "President Hr",
  "President It",
  "President Marketing",
  "President Operations",
  "President Projects",
  "President Sales",
  "President Sales And Marketing",
  "Principal",
  "Principal Application Engineer",
  "Principal Architect",
  "Principal Consultant",
  "Principal Engineer",
  "Principal Product Manager",
  "Principal Software Developer",
  "Principal Software Engineer",
  "Process Analyst",
  "Process Associate",
  "Process Consultant",
  "Process Designer",
  "Process Engineer",
  "Process Executive",
  "Process Lead",
  "Process Manager",
  "Process Specialist",
  "Procurement Analyst",
  "Procurement Assistant",
  "Procurement Associate",
  "Procurement Coordinator",
  "Procurement Engineer",
  "Procurement Executive",
  "Procurement Head",
  "Procurement Manager",
  "Procurement Officer",
  "Procurement Specialist",
  "Product Analyst",
  "Product Designer",
  "Product Manager",
  "Product Owner",
  "Product Specialist",
  "Product Trainer",
  "Production and Support Engineer",
  "Production Engineer",
  "Production Manager",
  "Production Supervisor",
  "Program Advisor",
  "Program Coordinator",
  "Program Developer",
  "Program Engineer",
  "Program Head",
  "Program Lead",
  "Program Manager",
  "Programmer",
  "Programmer Analyst",
  "Project Analyst",
  "Project And Technical Lead",
  "Project Coordinator",
  "Project Engineer",
  "Project Executive",
  "Project Head",
  "Project Lead",
  "Project Management Analyst",
  "Project Management Officer",
  "Project Manager",
  "Python Architect",
  "Python Automation Engineer",
  "Python Automation Tester",
  "Python Consultant",
  "Python Developer Lead",
  "Python Engineer",
  "Python Programmer",
  "Python Software Developer",
  "Python Tester",
  "Python Trainer",
  "Quality Analyst",
  "Quality Assurance Lead",
  "Quality Assurance Manager",
  "Quality Assurance Tester",
  "Quality Auditor",
  "Quality Engineer",
  "Quality Incharge",
  "Quality Manager",
  "Quality Test Engineer",
  "React Developer",
  "React JS Developer",
  "React Js Frontend Developer",
  "React Js Software Engineer",
  "React Lead",
  "React Native Developer",
  "Recruiter",
  "Recruiter Advisor",
  "Recruiter Analyst",
  "Recruiter Consultant",
  "Recruiter Coordinator",
  "Recruiter Manager",
  "Recruiter Officer",
  "Recruiter Specialist",
  "Recruiter Trainee",
  "Regional Business Manager",
  "Regional Head",
  "Regional Head Sales",
  "Regional Human Resource Manager",
  "Regional Manager",
  "Regional Operations Manager",
  "Regional Sales Manager",
  "Regional Sales Officer",
  "Regional Trainer",
  "Regional Training Manager",
  "Relationship Associate",
  "Relationship Commercial Banking Manager",
  "Relationship Dealing Manager",
  "Relationship Executive",
  "Relationship Lead",
  "Relationship Manager",
  "Relationship Officer",
  "Relationship Partner",
  "Relationship Wealth Management Manager",
  "Relationship Wealth Manager",
  "Reliability Analyst",
  "Reliability And Safety Engineer",
  "Reliability Engineer",
  "Reliability Expert",
  "Reliability Lead",
  "Reliability Manager",
  "Reliability Technician",
  "Reliability Testing Engineer",
  "Research Analyst",
  "Research And Development Chemist",
  "Research And Development Manager",
  "Research And Development Officer",
  "Research Associate",
  "Research Chemist",
  "Research Development Engineer",
  "Research Executive",
  "Research Manager",
  "Research Scientist",
  "Retail and Store Manager",
  "Retail Executive",
  "Retail Manager",
  "Retail Merchandiser",
  "Retail Sales Executive",
  "Retail Sales Manager",
  "Retail Sales Officer",
  "Retail Trainer",
  "Retailer",
  "Risk Advisor",
  "Risk Analyst",
  "Risk Consultant",
  "Risk Engineer",
  "Risk Executive",
  "Risk Investigator",
  "Risk Management Analyst",
  "Risk Management Executive",
  "Risk Manager",
  "Risk Officer",
  "Sales Associate",
  "Sales Coordinator",
  "Sales Engineer",
  "Sales Executive",
  "Sales Head",
  "Sales Manager",
  "Sales Officer",
  "Sales Representative",
  "Sales Team Lead",
  "Salesforce Developer",
  "Scientist",
  "Scientist Engineer",
  "Scientist Fellow",
  "Scientist Trainee",
  "Security Administrator",
  "Security Analyst",
  "Security Architect",
  "Security Consultant",
  "Security Engineer",
  "Security Manager",
  "Security Officer",
  "Security Specialist",
  "Security Supervisor",
  "Senior Accountant",
  "Senior Business Analyst",
  "Senior Developer",
  "Senior Java Developer",
  "Senior Manager",
  "Senior Sales Executive",
  "Senior Sales Manager",
  "Senior Sales Officer",
  "Senior Software Developer",
  "Senior Software Engineer",
  "Site Accountant",
  "Site Coordinator",
  "Site Engineer",
  "Site Head",
  "Site Incharge",
  "Site Lead",
  "Site Manager",
  "Site Reliability Engineer",
  "Site Supervisor",
  "Sitecore Developer",
  "Software Application Developer",
  "Software Architect",
  "Software Developer",
  "Software Development Engineer",
  "Software Development Manager",
  "Software Development Test Engineer",
  "Software Engineer",
  "Software Programmer",
  "Software Test Engineer",
  "Software Tester",
  "Solution Analyst",
  "Solution Architect",
  "Solution Consultant",
  "Solution Designer",
  "Solution Developer",
  "Solution Engineer",
  "Solution Expert",
  "Solution Lead",
  "Solution Manager",
  "Solution Specialist",
  "Specialist Analyst",
  "Specialist Designer",
  "Specialist Developer",
  "Specialist Engineer",
  "Specialist Officer",
  "Specialist Trainer",
  "Stack Developer",
  "Strategy Analyst",
  "Strategy Associate",
  "Strategy Consultant",
  "Strategy Executive",
  "Strategy Intern",
  "Strategy Lead",
  "Strategy Manager",
  "Strategy Officer",
  "Strategy Program Manager",
  "Supply Chain Analyst",
  "Supply Chain Assistant",
  "Supply Chain Consultant",
  "Supply Chain Coordinator",
  "Supply Chain Engineer",
  "Supply Chain Executive",
  "Supply Chain Manager",
  "Supply Chain Officer",
  "Supply Executive",
  "Supply Planner",
  "Support Administrator",
  "Support Analyst",
  "Support Consultant",
  "Support Engineer",
  "Support Executive",
  "Support Lead",
  "Support Manager",
  "Support Specialist",
  "System Administrator",
  "System Analyst",
  "System and Windows Administrator",
  "System Architect",
  "System Engineer",
  "System Integrator",
  "System Manager",
  "System Support Engineer",
  "Talent Acquisition Consultant",
  "Talent Acquisition Coordinator",
  "Talent Acquisition Executive",
  "Talent Acquisition Lead",
  "Talent Acquisition Manager",
  "Talent Acquisition Specialist",
  "Talent Acquisition Team Lead",
  "Talent Advisor",
  "Talent Manager",
  "Talent Sourcer",
  "Tax Accountant",
  "Tax Advisor",
  "Tax Analyst",
  "Tax Associate",
  "Tax Consultant",
  "Tax Manager",
  "Tax Specialist",
  "Taxation Executive",
  "Taxation Head",
  "Taxation Officer",
  "Technical Architect",
  "Technical Consultant",
  "Technical Content Writer",
  "Technical Lead",
  "Technical Manager",
  "Technical Project Manager",
  "Technical Recruiter",
  "Technical Support Engineer",
  "Technical Writer",
  "Technology Analyst",
  "Technology Architect",
  "Technology Consultant",
  "Technology Engineer",
  "Technology Lead",
  "Technology Manager",
  "Technology Project Manager",
  "Technology Recruiter",
  "Technology Specialist",
  "Technology Trainer",
  "Test Analyst",
  "Test Architect",
  "Test Automation Architect",
  "Test Engineer",
  "Test Lead",
  "Test Specialist",
  "Tester",
  "Testing Engineering Analyst",
  "Testing Manager",
  "Training Administrator",
  "Training and Quality Manager",
  "Training Consultant",
  "Training Coordinator",
  "Training Executive",
  "Training Head",
  "Training Lead",
  "Training Manager",
  "Training Officer",
  "Training Specialist",
  "Treasury Accountant",
  "Treasury Analyst",
  "Treasury Consultant",
  "Treasury Dealer",
  "Treasury Executive",
  "Treasury Manager",
  "Treasury Officer",
  "Treasury Operations Manager",
  "Treasury Relationship Manager",
  "Treasury Specialist",
  "Ux And Ui Designer",
  "Ux And Visual Designer",
  "Ux Design Manager",
  "Ux Graphic Designer",
  "Ux Interaction Designer",
  "Ux Team Lead",
  "Ux Writer",
  "Vice President",
  "Vice President Engineering",
  "Vice President Finance",
  "Vice President Information Technology",
  "Vice President Market Development",
  "Vice President Operations",
  "Vice President Sales",
  "Vice President Technology",
] as const
